# Pantalla.
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
ORIGEN = (0, 0)

MID_WIDTH_SCREEN = SCREEN_WIDTH // 2
MID_HEIGHT_SCREEN = SCREEN_HEIGHT // 2
SCREEN_CENTER = (MID_WIDTH_SCREEN, MID_HEIGHT_SCREEN)

BOTON_START_SIZE = (100, 50)
BOTON_START_POS = (MID_WIDTH_SCREEN, 400)

ULTIMO_SCORE_POS = (50, 20)
MAX_SCORE_POS = (800, 20)
VIDAS_POS = (50, 20)

MESSAGE_START_POS = (MID_WIDTH_SCREEN, 400)


# Juego.
FPS = 30


# Jugador.
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
PLAYER_SPAWN_POINT_X = SCREEN_WIDTH // 2
PLAYER_SPAWN_POINT_Y = 500

PLAYER_SPEED = 15

VELOCIDAD_PROYECTIL = 20
PROYECTIL_WIDTH = 1
PROYECTIL_HEIGHT = 10

PROYECTIL_WIDTH = 6
PROYECTIL_HEIGHT = 16

ESCUDO_WIDTH = 32
ESCUDO_HIGHT = 32
VELOCIDAD_ESCUDO = 5


# Enemigos.
ABEJA_WIDTH = 20
ABEJA_HEIGHT = 20
CANTIDAD_ENEMIGOS = 25
VELOCIDAD_ABEJA = 10


# Direcciones.
move_left = False
move_right = False


# Colores.
BLACK = (0, 0, 0)
RED = (255, 0, 0)
MAGENTA = (255, 0, 255)
WHITE = (255, 255, 255)
CYAN = (0, 255, 255)
BLUE = (0, 0, 255)